list: $/bradley/calendar/models/calendar/columns.yaml
modelClass: Bradley\Calendar\Models\Calendar
title: Calendar
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'bradley/calendar/calendar/update/:id'
